version: '2'
services:
  postgres:
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=qweex
      - POSTGRES_PASSWORD=111111
      - POSTGRES_DB=qweex
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.0
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data